{% set version = "2.1.2" %}

package:
  name: stock-pandas
  version: {{ version }}

source:
  url: https://github.com/kaelzhang/stock-pandas/archive/refs/tags/{{ version }}.tar.gz
  sha256: e56af08a4a8f4c7dcd15ea65bc87c9c264ebdcec0b62f9c9a27f30c94f16963f

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - STOCK_PANDAS_BUILDING_EXT=1
  number: 1

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - Cython >=3.0.5,<4.0.0
    - numpy 2.0
    - pandas >=1.0.0
    - setuptools
  run:
    - python
    - pandas >=1.0.0

test:
  imports:
    - stock_pandas
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/kaelzhang/stock-pandas
  summary: 'The production-ready subclass of `pandas.DataFrame` to support stock statistics and indicators.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/kaelzhang/stock-pandas

extra:
  recipe-maintainers:
    - kaelzhang
